version: '2'
services:
    jhipsterreactmonolithic-app:
        image: jhipsterreactmonolithic
        external_links:
            - jhipsterreactmonolithic-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipsterReactMonolithic
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterreactmonolithic-mongodb:
        extends:
            file: mongodb.yml
            service: jhipsterreactmonolithic-mongodb
