version: '2'
services:
    jhipsterreactmonolithic-mongodb:
        container_name: jhipsterreactmonolithic-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/jhipsterReactMonolithic/mongodb/:/data/db/
